# This file should contain all the record creation needed to seed the database with its default values.
# The data can then be loaded with the rails db:seed command (or created alongside the database with db:setup).
#
# Examples:
#
#   movies = Movie.create([{ name: 'Star Wars' }, { name: 'Lord of the Rings' }])
#   Character.create(name: 'Luke', movie: movies.first)


subject_list = [
	[ 'GEOMETRIA  ANALÍTICA', 'MATA01', 'Álgebra vetorial. A translação e a rotação de eixos. A reta e o plano no espaço R3. As cônicas. As superfícies de revolução.' ],
	[ 'CÁLCULO A', 'MATA02', 'As funções polinomiais e as funções racionais. A interpolação por polinômios. O limite e a continuidade de funções reais de uma variável real: principais propriedades. A derivada de funções reais de uma variável real. As propriedades da derivada de tais funções. Os extremantes de funções reais de uma variável real e o polinômio de Taylor. A construção do gráfico de tais funções. A integral de uma função real definida em um intervalo limitado e fechado. Principais teoremas. O cálculo de primitivas de funções reais.' ],
	[ 'INTRODUÇÃO À LÓGICA DE PROGRAMAÇÃO', 'MATA37', 'Desenvolvimento de algoritmos.  Refinamento sucessivo.  Noções de especificação e correção de algoritmos.  Construção de programas aplicando conceitos de construção de algoritmos: variáveis, constantes, operadores aritméticos e expressões, estruturas de controle (atribuição, sequência, seleção, repetição, recursão).  Parâmetros.  Princípios de programação estruturada e modular.  Documentação de programas.  Teste de programas.  Análise de resultados.' ],
	[ 'PROJETO DE CIRCUITOS LÓGICOS', 'MATA38', 'Representação de dados;  Sistemas de numeração;  aritmética binária e hexadecimal;  números em ponto fixo e ponto flutuante;  representação de caracteres;  Eletrônica digital básica.   Noções de circuitos e componentes eletrônicos.   Famílias lógicas - construção e características elétricas.   Circuitos integrados.   Funções booleanas.   Circuitos combinacionais e seqënciais.   Circuitos básicos de uma máquina: Flip flops, registradores, contadores, memórias ROM e RAM.   Decodificadores, ALU,.   Considerações sobre a velocidade de operação dos circuitos lógicos.   Exercícios práticos em laboratório.' ],
	[ 'SEMINÁRIOS DE INTRODUÇÃO AO CURSO', 'MATA39', 'Temas relacionados com a área de computação (introdução aos sstemas de computação, história da computação e outros).   Temas relacionados à aplicação da computação em outras áreas.   Aspectos éticos relacionados ao uso da computação em atividades humanas.   Temas relacionados à integração do estudante na vida acadêmica (estrutura e organização da universidade, o papel do estudante em atividades de extensão e pesquisa, utilização da biblioteca , atividades extra curriculares, etc.).  Iniciação prática ao uso do sistema operacional utilizado nos laboratórios do curso.' ],
	[ 'MATEMÁTICA DISCRETA I', 'MATA42', 'Relações.  Relações de equivalência.  Partição.  Representação.  Funções.  Recursão.  Conjuntos finitos e infinitos.  Cardinalidade.  Enumerabilidade.  Diagonalização de Cantor, Prinípio da indução. Análise combinatória:  Enumeração por recursão;  Contagem;  Arranjo;  Permutação;  Combinação simples e com repetição.' ],
	[ 'ÁLGEBRA LINEAR A', 'MATA07', 'Matrizes e sistemas lineares. Espaços vetoriais. Produto interno. Transformações lineares. Diagonalização de operadores.' ],
	[ 'ESTRUTURAS DE DADOS E ALGORITMOS I', 'MATA40', 'Introdução à análise de algoritmos.  Tipos Abstratos de Dados.  Estruturas de dados fundamentais: listas, filas, pilhas, árvores e heaps.  Algoritmos de busca em memória principal.' ],
	[ 'ARQUITETURA DE COMPUTADORES', 'MATA48', 'A máquina de von Neumann: conceito, arquitetura lógica e funcional; unidades funcionais: cpu, memória: memória cache; dispositivos de e/s e barramento.  Tipos de instrução e de endereçamento, fluxo de controle.  Memória virtual, instruções de e/s virtuais, instruções virtuais para processamento paralelo.  Mecanismos de interrupção.  Arquiteturas micro e nanoprogramadas.  Introdução à arquiteturas avançadas: pipeline, múltiplas unidades funcionais e máquinas paralelas: processadores RISC e CISC: conceito de máquina virtual: tendências.  Noções de avaliação de desempenho e importância da corretude dos dados estatísticos gerados pela avaliação.  Impactos sócio-ambientais do ciclo de vida do hardware.' ],
	[ 'LABORATÓRIO DE PROGRAMAÇÃO I', 'MATA57', 'Estudo das linguagens C e C++ através da implementação de programas nestas linguagens.' ],
	[ 'COMPLEMENTOS DE CÁLCULO', 'MATA95', 'Aplicações de integrais simples.  Conceito, propriedade e aplicações de integrais duplas.  As derivadas parciais de funções reais de duas variáveis.  O conceito de diferenciabilidadew e a construção do plano tangente ao gráfico de tais funções.  As curvas de nível.  Noções de equações diferenciais.  Noções das séries de potências e das séries de Fourier.' ],
	[ 'MATEMÁTICA DISCRETA II', 'MATA97', 'Números naturais.  Números inteiros.  Divisores e números primos.  Congruência.  Critérios de divisibilidade.  Números racionais.  Estruturas algébricas.  Homomorfismo.  Isomorfismo.  Relações de ordem:  pré-ordem, ordem parcial, ordem total.  Reticulados:  modular. distribuido, completo.  Ponto fixo.  Álgebra de Boole.' ],
	[ 'ELEMENTOS DO ELETROMAGNETISMO E DE CIRCUITOS ELÉTRICOS', 'FISA75', 'Teórica:  Fundamentos da Mecânica Clássica.  Aplicações de oscilações mecânicas livres, amortecidas e forçadas.  Fundamentos da eletricidade.  Fundamentos do magnetirmo.  Circuitos elétricos.  Capacitores.  Indutores.  Circuitos RC e RL.  Prática:  Medida de corrente e diferença de potencial.  Resistências não lineares por efeito da temperatura.  Linhas equipotenciais.  Balança de corrente.  Constante de tempo em circuitos RC.  Medida da componente horizontal do campo magnético da terra.' ],
	[ 'MÉTODOS ESTATÍSTICOS', 'MAT236', 'Aspectos preliminares do trabalho estatístico. Séries estatísticas e representação gráfica. Médias. Separatrizes. Principais medidas de dispersão. Conceito, teoremas e leis de probabilidade. Distribuições de probabilidades. Distribuições amostrais. Intervalos de confiança. Teste de hipótese. Correlação e regressão linear simples. Ajustamento de funções matemáticas pelo método dos mínimos quadrados.' ],
	[ 'LÓGICA PARA COMPUTAÇÃO', 'MATA47', 'Técnicas de demonstração.  Conceito de Lógica:  sintaxe, semântica.  Propriedades da lógica clássica.  Lógica Proposicional e de Primeira Ordem.  Métodos dedutivos como:  axiomático, dedução natural, cálculo de sequentes, tableaux, resolução.  Conceito de correção e completeza.  Aplicações da lógica.' ],
	[ 'PROGRAMAÇÃO DE SOFTWARE BÁSICO', 'MATA49', 'Programação em linguagem de montagem.  Formato e classificação de instruções.  Conjuntos de instruções e modos de endereçamento.  Manipulação de pilhas.  SUbrotinas:  tipos, características e passagem de parâmetros.  Interrupções de software.  Recursos de arquitetura para técnicas de programação.  Montagem e ligação.  Nesta disciplina serão introduzidos conceitos de implementação de baixo nível utilizando as linguagens C e Assembler.' ],
	[ 'LINGUAGENS FORMAIS E AUTÔMATOS', 'MATA50', 'Conceito de linguagem.  Hierarquia de Chomsky.  Linguagens regulares e expressões regulares.  Reconhecedores, geradores e propriedades das linguagens discriminadas na hierarquia de Chomsky.  Ambiguidade e simplificação de gramáticas livres de contexto.  Formas normais de gramáticas livres de contexto.' ],
	[ 'PROGRAMAÇÃO ORIENTADA A OBJETOS', 'MATA55', 'Conceitos de Orientação a Objetos. Programação orientada a objetos: Implementação de classes, herança, polimorfismo, comunicação e associação. Conceito de reuso. Exemplos de implementação dos conceitos estudados em mais de uma linguagem orientada a objeto. Trabalhos práticos em Java e/ou outras linguagens.' ],
	[ 'METODOLOGIA E EXPRESSÃO TÉCNICO-CIENTÍFICA', 'FCHC45', 'Visão geral dos Princípios Filosóficos e Epistemológicos das Ciências.  O processo da pesquia (formulação do problema da pesquisa; processo de observação; ordenação dos dados).  Planejamento da pesquisa.  Os meios e técnicas de comunicação dos resultados da pesquisa (relatório; estudos monográficos; artigos técnicos; estudos explicativos; técnicas de preparação do material para exposições).' ],
	[ 'TEORIA DA COMPUTAÇÃO', 'MATA51', 'Modelos e Computação: máquinas de Turing, funções recursivas, - Cálculus, Tese de Church, Linguagens inumeráveis, recursivamente enumeráveis e recursivas.  Decibilidade.  Redução.  Problemas indecidíveis.  Incompletude da aritmética.' ],
	[ 'ANÁLISE E PROJETO DE ALGORITMOS', 'MATA52', 'Análise de complexidade de algoritmos.  Técnicas de projeto eficiente de algoritmos: recursão, dividir para conquistar, programação dinâmica, programação gulosa, backtracking.  Algoritmos de classificação interna.  Algoritmos envolvendo sequências e conjuntos.  Algoritmos probabilísticos.  Algoritmos geométricos.  Noções de Algoritmos Paralelos.  Noções de NP-completude.' ],
	[ 'SISTEMAS OPERACIONAIS', 'MATA58', 'Estruturas de sitemas operacionais.   Sistemas operacionais centralizados:  gerenciamento de processos;  mecanismos de comunicação entre processos;  sincronização de processos;  mecanismos de entrada e saida;  gerenciamento de memória;  sistemas de arquivos; proteção e segurança.   Introdução a sistemas distribuidos.   Estudos de casos de sistemas operacionais existentes.   Aspectos éticos relacionados à segurança de sistemas.' ],
	[ 'COMPILADORES', 'MATA61', 'Análise e Síntese.  Análise léxica, sintática e semântica.  Geração de código intermediário.  Otimização de código intermediário.  Geração e otimização de código objeto.' ],
	[ 'COMPUTADOR, ÉTICA E SOCIEDADE', 'MATA68', 'O papel do computador na sociedade contemporânea: impactos, consequências e tendências.  Os novos paradigmas da sociedade da informação e seus aspectos econômicos, sociais, políticos, éticos, culturais e educacionais.  Ética e a profissão.  Direitos  e deveres do profissional.  Associações, órgãos de classe e seus objetivos.' ],
	[ 'TEORIA DOS GRAFOS', 'MATA53', 'Grafos, grafos simples, subgrafos.  Isomorfismo de grafos. Representação computacional.   Algoritmos de buscas. Grafos orientados. Trilhas, caminhos e ciclos. Distância. Caminho mínimo. Conectividade de vértices e arestas. Grafos hamiltonianos. Problemas de caixeiro viajante. Grafos eulerianos. Problema do carteiro chinês. Árvores, árvore geradora mínima. Teoria do NP completo.   Classes P, NP, NP-completo, NP-Difícil. Reduções polinomiais. Prova de NP-completude. Noções de planaridade. Noções de coloração de vértices. Número cromático. Noções de casamentos.   Casamentos perfeitos. Noções de fluxos em redes.' ],
	[ 'ESTRUTURAS DE DADOS E ALGORITMOS II', 'MATA54', 'Dispositivos de armazenamento secundário.  Algoritmos de busca em texto.  Arquivos com organização sequencial ( busca sequencial, busca por interpolação, busca binária).  Arquivos com organização direta ( funções de hashing, métodos de resolução  de colisão).  Arquivos com organização em árvore (árvores-B e suas variações).  Busca aproximada de padrões.  Busca por chave secundária.  Busca por faixas de valores.  Ordenação externa.  Compressão.' ],
	[ 'REDES DE COMPUTADORES I', 'MATA59', 'Introdução a redes de computadores: terminologia, topologias, tipos de redes, software e hardware de rede, arquiteturas e modelos de referência.   Detalhamento de cada uma das camadas: física, enlace, subcamada de acesso ao meio, rede, transporte, sessão, apresentação e aplicação, considerando-se diferentes tipos de rede.   Introdução a serviços de redes ( serviço de nomes, correio eletrônico, sistemas de arquivos distribuidos).   Segurança em redes.   Aspectos éticos relacionados à gerência e uso de redes.' ],
	[ 'ENGENHARIA DE SOFTWARE I', 'MATA62', 'Introdução a Engenharia de Software. Modelos de processos de desenvolvimento de software. Organização e planejamento de projeto. Modelagem e especificação de requisitos de software. Análise de requisitos de software. Verificação e validação de requisitos de software. Métodos estruturados. Métodos orientados a objetos. Noções de métodos formais para especificação e verificação de requisitos. Ferramentas para engenharia de requisitos. Métricas de requisitos de software. Requisitos e prototipagem de interfaces.' ],
	[ 'PARADIGMAS DE LINGUAGENS DE PROGRAMAÇÃO A', 'MATE12', 'Estudos do paradigma funcional: conceito de programação funcional; resolução e implementação de problemas numa linguagem funcional; modelo de implementação. Estudo do paradigma lógico: conceito de programação lógica; resolução e implementação de problemas numa linguagem lógica; modelo de implementação. Uma análise comparativa geral entre os paradigmas imperativo, orientado a objetos, funcional, lógico, concorrente.' ],
	[ 'BANCO DE DADOS', 'MATA60', 'Arquitetura geral de um SGBD.  Modelos de Entidades e Relacionamentos (ER) e suas extensões.  O modelo relacional.  Mapeamento de um projeto ER em um projeto relacional.  Linguagem de definição e manipulação de dados.  Álgebra e cálculo relacional.  Mapeamento de consultas em álgebra e cálculo relacional em SQL.  Normalização. Mecanismo de otimização de consultas.  Introdução aos modelos de rede, hierárquico e orientado a objetos.  Projeto físico de banco de dados.  Gerenciamento de transações e controle de concorrência.  Mecanismos de recuperação de falhas.   Introdução a um banco de dados distribuidos.  Aspectos éticos relacionados ao uso de  banco de dados.' ],
	[ 'INTELIGÊNCIA ARTIFICIAL', 'MATA64', 'Fundamentos.  Agentes inteligentes.  Resolução de problemas por busca.  Representação de conhecimento:  lógica, regras, redes semânticas, quadros (frames).  Técnicas de raciocínio automático.  Programação de agentes inteligentes.  Introdução à IA Conexionista.  Noções de IA Distribuida, planejamento, tratamento de incertezas,  aprendizado de máquina. Aspectos éticos relacionados à inteligência artificial.' ],
	[ 'COMPUTAÇÃO GRÁFICA', 'MATA65', 'Introdução.  Primitivas Gráficas.  Transformações 2D.  Cor.  Transformações 3D.  Modelos de iluminação.  Introdução ao processamento de imagens e realidade virtual.' ],
	[ 'FUNDAMENTOS DE SISTEMAS DISTRIBUÍDOS', 'MATA88', 'Caracterização de sistemas distribuidos.  Modelos de sistemas distribuidos.  Arquiteturas Cliente-Servidor e Par-a-Par.  Comunicação entre processos (mecanismos de troca de mensagens, RPC, RMI.  Espaço de Tuplas, Eventos, Introdução à Comunicação em Grupo, comunicação via memória compartilhada).  Serviços distribuidos de arquivos.  Seviços de resolução de nomes.  Agentes Móveis.  Introdução à Computação Ubíqua.  Exemplos de sistemas e plataformas distribuidas.' ],
	[ 'ENGENHARIA DE SOFTWARE II-A', 'MATE11', 'Modelos de processos de desenvolvimento de sogtware. Organização e planejamento de projeto. Modelagem e especificação de requisitos de software. Análise de requisitos de software. Verificação e validação de requisitos de software. Métodos estruturados. Métodos orientados a objetos. Noções de métodos formais para especificação e verificação de requisitos. Ferramentas para engenharia de requisitos. Métricas de requisitos de software. Requisitos e prototipagem de interfaces.' ],
	[ 'PROJETO FINAL DE CURSO I', 'MATA66', 'O aluno desenvolverá uma proposta de trabalho final em uma área da computação de seu interesse, orientado por um professor, e fará uma defesa da proposta apresentando o projeto escrito da mesma.' ],
	[ 'PROJETO FINAL DE CURSO II', 'MATA67', 'O aluno desenvolverá o trabalho proposto anteriormente na disciplina de Projeto Final do Curso I e apresentará uma monografia, fazendo a defesa final do trabalho.' ],
]


subject_list.each do |name, code, about|
	Subject.create( name: name, code: code, about: about )
end


class_subject_list = [
	[ 'T01', '["TER", "QUI"]', '07:00', '08:50', 'MATA01' ],
	[ 'T02', '["TER", "QUI"]', '07:00', '08:50', 'MATA01' ],
	[ 'T03', '["TER", "QUI"]', '08:50', '10:40', 'MATA01' ],
	[ 'T04', '["TER", "QUI"]', '08:50', '10:40', 'MATA01' ],
	[ 'T05', '["TER", "QUI"]', '10:40', '12:30', 'MATA01' ],
	[ 'T06', '["TER", "QUI"]', '10:40', '12:30', 'MATA01' ],
	[ 'T07', '["TER", "QUI"]', '13:00', '14:50', 'MATA01' ],
	[ 'T08', '["TER", "QUI"]', '14:50', '16:40', 'MATA01' ],
	[ 'T09', '["TER", "QUI"]', '16:40', '18:30', 'MATA01' ],
	[ 'T10', '["TER", "QUI"]', '18:30', '20:20', 'MATA01' ],
	[ 'T11', '["TER", "QUI"]', '20:20', '22:10', 'MATA01' ],
	[ 'T12', '["SEG", "QUA"]', '14:50', '16:40', 'MATA01' ],
	[ 'T13', '["SEG", "QUA"]', '18:30', '20:20', 'MATA01' ],
	[ 'T01', '["SEG", "QUA", "SEX"]', '07:00', '08:50', 'MATA02' ],
	[ 'T02', '["SEG", "QUA", "SEX"]', '07:00', '08:50', 'MATA02' ],
	[ 'T03', '["SEG", "QUA", "SEX"]', '07:00', '08:50', 'MATA02' ],
	[ 'T04', '["SEG", "QUA", "SEX"]', '08:50', '10:40', 'MATA02' ],
	[ 'T05', '["SEG", "QUA", "SEX"]', '08:50', '10:40', 'MATA02' ],
	[ 'T06', '["SEG", "QUA", "SEX"]', '13:00', '14:50', 'MATA02' ],
	[ 'T07', '["SEG", "QUA", "SEX"]', '13:00', '14:50', 'MATA02' ],
	[ 'T08', '["SEG", "QUA", "SEX"]', '13:00', '14:50', 'MATA02' ],
	[ 'T09', '["SEG", "QUA", "SEX"]', '14:50', '16:40', 'MATA02' ],
	[ 'T10', '["SEG", "QUA", "SEX"]', '16:40', '18:30', 'MATA02' ],
	[ 'T11', '["SEG", "QUA", "SEX"]', '18:30', '20:20', 'MATA02' ],
	[ 'T12', '["SEG", "QUA", "SEX"]', '20:20', '22:10', 'MATA02' ],
	[ 'P01', '["SEX"]', '18:30', '20:20', 'MATA37' ],
	[ 'P02', '["QUI"]', '14:50', '16:40', 'MATA37' ],
	[ 'P03', '["QUI"]', '16:40', '18:30', 'MATA37' ],
	[ 'P04', '["QUI"]', '18:30', '20:20', 'MATA37' ],
	[ 'T01', '["QUA"]', '20:20', '22:10', 'MATA37' ],
	[ 'T02', '["TER"]', '14:50', '16:40', 'MATA37' ],
	[ 'T03', '["TER"]', '16:40', '18:30', 'MATA37' ],
	[ 'T04', '["TER"]', '18:30', '20:20', 'MATA37' ],
	[ 'P01', '["QUI"]', '08:50', '10:40', 'MATA38' ],
	[ 'P02', '["QUI"]', '13:00', '14:50', 'MATA38' ],
	[ 'P03', '["QUI"]', '18:30', '20:20', 'MATA38' ],
	[ 'T01', '["TER"]', '08:50', '10:40', 'MATA38' ],
	[ 'T02', '["TER"]', '13:00', '14:50', 'MATA38' ],
	[ 'T03', '["TER"]', '18:30', '20:20', 'MATA38' ],
	[ 'T01', '["SEG", "SEG", "SEG"]', '16:40', '17:35', 'MATA39' ],
	[ 'P01', '["QUI"]', '14:50', '16:40', 'MATA42' ],
	[ 'T01', '["TER"]', '14:50', '16:40', 'MATA42' ],
	[ 'T01', '["TER", "QUI"]', '10:40', '12:30', 'MATA07' ],
	[ 'T02', '["TER", "QUI"]', '10:40', '12:30', 'MATA07' ],
	[ 'T03', '["TER", "QUI"]', '13:00', '14:50', 'MATA07' ],
	[ 'T04', '["TER", "QUI"]', '14:50', '16:40', 'MATA07' ],
	[ 'T05', '["TER", "QUI"]', '20:20', '22:10', 'MATA07' ],
	[ 'T06', '["SEG", "QUA"]', '08:50', '10:40', 'MATA07' ],
	[ 'T07', '["SEG", "QUA"]', '10:40', '12:30', 'MATA07' ],
	[ 'T08', '["SEG", "QUA"]', '10:40', '12:30', 'MATA07' ],
	[ 'T09', '["SEG", "QUA"]', '16:40', '18:30', 'MATA07' ],
	[ 'T10', '["TER", "QUI"]', '13:00', '14:50', 'MATA07' ],
	[ 'P01', '["QUI"]', '16:40', '18:30', 'MATA40' ],
	[ 'P02', '["QUI"]', '18:30', '20:20', 'MATA40' ],
	[ 'P03', '["QUI"]', '18:30', '20:20', 'MATA40' ],
	[ 'T01', '["TER"]', '16:40', '18:30', 'MATA40' ],
	[ 'T02', '["TER"]', '18:30', '20:20', 'MATA40' ],
	[ 'T03', '["TER"]', '18:30', '20:20', 'MATA40' ],
	[ 'P01', '["QUI"]', '14:50', '16:40', 'MATA48' ],
	[ 'T01', '["TER"]', '14:50', '16:40', 'MATA48' ],
	[ 'P01', '["SEG"]', '15:45', '18:30', 'MATA57' ],
	[ 'P01', '["SEX"]', '13:00', '14:50', 'MATA95' ],
	[ 'T01', '["SEG", "QUA"]', '13:00', '14:50', 'MATA95' ],
	[ 'P01', '["QUA"]', '14:50', '16:40', 'MATA97' ],
	[ 'T01', '["SEG"]', '14:50', '16:40', 'MATA97' ],
	[ 'P01', '["SEG"]', '14:50', '16:40', 'FISA75' ],
	[ 'T01', '["QUA", "SEX"]', '14:50', '16:40', 'FISA75' ],
	[ 'T01', '["QUA", "SEX"]', '18:30', '20:20', 'MAT236' ],
	[ 'T02', '["SEG", "QUA"]', '13:00', '14:50', 'MAT236' ],
	[ 'T03', '["SEG", "QUA"]', '14:50', '16:40', 'MAT236' ],
	[ 'T04', '["TER", "QUI"]', '07:00', '08:50', 'MAT236' ],
	[ 'T05', '["TER", "QUI"]', '08:50', '10:40', 'MAT236' ],
	[ 'T06', '["TER", "QUI"]', '08:50', '10:40', 'MAT236' ],
	[ 'T07', '["TER", "QUI"]', '10:40', '12:30', 'MAT236' ],
	[ 'T08', '["TER", "QUI"]', '14:50', '16:40', 'MAT236' ],
	[ 'T09', '["TER", "QUI"]', '16:40', '18:30', 'MAT236' ],
	[ 'T10', '["TER", "QUI"]', '18:30', '20:20', 'MAT236' ],
	[ 'T11', '["TER", "QUI"]', '20:20', '22:10', 'MAT236' ],
	[ 'T01', '["TER", "QUI"]', '16:40', '18:30', 'MATA47' ],
	[ 'P01', '["QUA"]', '16:40', '18:30', 'MATA49' ],
	[ 'T01', '["SEG"]', '16:40', '18:30', 'MATA49' ],
	[ 'P01', '["QUI"]', '13:00', '14:50', 'MATA50' ],
	[ 'T01', '["TER"]', '13:00', '14:50', 'MATA50' ],
	[ 'P01', '["QUA"]', '13:00', '14:50', 'MATA55' ],
	[ 'T01', '["SEG"]', '13:00', '14:50', 'MATA55' ],
	[ 'T01', '["SEG", "QUA"]', '14:50', '16:40', 'FCHC45' ],
	[ 'P01', '["QUI"]', '14:50', '16:40', 'MATA51' ],
	[ 'P02', '["QUI"]', '18:30', '20:20', 'MATA51' ],
	[ 'T01', '["TER"]', '14:50', '16:40', 'MATA51' ],
	[ 'T02', '["TER"]', '18:30', '20:20', 'MATA51' ],
	[ 'P01', '["QUI"]', '16:40', '18:30', 'MATA52' ],
	[ 'T01', '["TER"]', '16:40', '18:30', 'MATA52' ],
	[ 'P01', '["QUA"]', '13:00', '14:50', 'MATA58' ],
	[ 'P02', '["QUI"]', '20:20', '22:10', 'MATA58' ],
	[ 'T01', '["SEG"]', '13:00', '14:50', 'MATA58' ],
	[ 'T02', '["TER"]', '20:20', '22:10', 'MATA58' ],
	[ 'P01', '["SEG"]', '16:40', '18:30', 'MATA61' ],
	[ 'T01', '["QUA"]', '16:40', '18:30', 'MATA61' ],
	[ 'P01', '["QUA"]', '19:25', '21:15', 'MATA68' ],
	[ 'P02', '["a combinar"]', '00:00', '00:00', 'MATA68' ],
	[ 'T01', '["QUA"]', '18:30', '19:25', 'MATA68' ],
	[ 'T02', '["QUA"]', '18:30', '20:20', 'MATA68' ],
	[ 'P01', '["QUI"]', '16:40', '18:30', 'MATA53' ],
	[ 'T01', '["TER"]', '16:40', '18:30', 'MATA53' ],
	[ 'P01', '["QUA"]', '16:40', '18:30', 'MATA54' ],
	[ 'T01', '["SEG"]', '16:40', '18:30', 'MATA54' ],
	[ 'P01', '["SEX"]', '18:30', '20:20', 'MATA59' ],
	[ 'P02', '["QUI"]', '14:50', '16:40', 'MATA59' ],
	[ 'P03', '["QUI"]', '20:20', '22:10', 'MATA59' ],
	[ 'T01', '["QUA"]', '18:30', '20:20', 'MATA59' ],
	[ 'T02', '["TER"]', '14:50', '16:40', 'MATA59' ],
	[ 'T03', '["TER"]', '20:20', '22:10', 'MATA59' ],
	[ 'P01', '["QUA"]', '14:50', '16:40', 'MATA62' ],
	[ 'P02', '["QUI"]', '18:30', '20:20', 'MATA62' ],
	[ 'T01', '["SEG"]', '14:50', '16:40', 'MATA62' ],
	[ 'T02', '["TER"]', '18:30', '20:20', 'MATA62' ],
	[ 'P01', '["QUI"]', '16:40', '18:30', 'MATA60' ],
	[ 'T01', '["TER"]', '16:40', '18:30', 'MATA60' ],
	[ 'P01', '["QUA"]', '14:50', '16:40', 'MATA64' ],
	[ 'T01', '["SEG"]', '14:50', '16:40', 'MATA64' ],
	[ 'P01', '["QUI"]', '14:50', '16:40', 'MATA65' ],
	[ 'T01', '["TER"]', '14:50', '16:40', 'MATA65' ],
	[ 'P01', '["QUA"]', '18:30', '19:25', 'MATA88' ],
	[ 'T01', '["QUA"]', '19:25', '21:15', 'MATA88' ],
	[ 'T01', '["a combinar"]', '00:00', '23:00', 'MATA66' ],
	[ 'T02', '["a combinar"]', '00:00', '23:00', 'MATA66' ],
	[ 'T03', '["a combinar"]', '00:00', '23:00', 'MATA66' ],
	[ 'T04', '["a combinar"]', '00:00', '23:00', 'MATA66' ],
	[ 'T05', '["a combinar"]', '00:00', '23:00', 'MATA66' ],
	[ 'T06', '["a combinar"]', '00:00', '23:00', 'MATA66' ],
	[ 'T07', '["a combinar"]', '00:00', '23:00', 'MATA66' ],
	[ 'T08', '["a combinar"]', '00:00', '23:00', 'MATA66' ],
	[ 'T09', '["a combinar"]', '00:00', '23:00', 'MATA66' ],
	[ 'T10', '["a combinar"]', '00:00', '23:00', 'MATA66' ],
	[ 'T11', '["a combinar"]', '00:00', '23:00', 'MATA66' ],
	[ 'T12', '["a combinar"]', '00:00', '23:00', 'MATA66' ],
	[ 'T13', '["a combinar"]', '00:00', '23:00', 'MATA66' ],
	[ 'T14', '["a combinar"]', '00:00', '23:00', 'MATA66' ],
	[ 'T15', '["a combinar"]', '00:00', '23:00', 'MATA66' ],
	[ 'T16', '["a combinar"]', '00:00', '23:00', 'MATA66' ],
	[ 'T17', '["a combinar"]', '00:00', '23:00', 'MATA66' ],
	[ 'T18', '["a combinar"]', '00:00', '23:00', 'MATA66' ],
	[ 'T19', '["a combinar"]', '00:00', '23:00', 'MATA66' ],
	[ 'T20', '["a combinar"]', '00:00', '23:00', 'MATA66' ],
	[ 'T21', '["a combinar"]', '00:00', '23:00', 'MATA66' ],
	[ 'T22', '["a combinar"]', '00:00', '23:00', 'MATA66' ],
	[ 'T23', '["a combinar"]', '00:00', '23:00', 'MATA66' ],
	[ 'T24', '["a combinar"]', '00:00', '23:00', 'MATA66' ],
	[ 'T25', '["a combinar"]', '00:00', '23:00', 'MATA66' ],
	[ 'T26', '["a combinar"]', '00:00', '23:00', 'MATA66' ],
	[ 'T27', '["a combinar"]', '00:00', '23:00', 'MATA66' ],
	[ 'T28', '["a combinar"]', '00:00', '23:00', 'MATA66' ],
	[ 'T29', '["a combinar"]', '00:00', '23:00', 'MATA66' ],
	[ 'T30', '["a combinar"]', '00:00', '23:00', 'MATA66' ],
	[ 'T31', '["a combinar"]', '00:00', '23:00', 'MATA66' ],
	[ 'T32', '["a combinar"]', '00:00', '23:00', 'MATA66' ],
	[ 'T33', '["a combinar"]', '00:00', '23:00', 'MATA66' ],
	[ 'T34', '["a combinar"]', '00:00', '23:00', 'MATA66' ],
	[ 'P01', '["a combinar"]', '00:00', '23:00', 'MATA67' ],
	[ 'P02', '["a combinar"]', '00:00', '23:00', 'MATA67' ],
	[ 'P03', '["a combinar"]', '00:00', '23:00', 'MATA67' ],
	[ 'P04', '["a combinar"]', '00:00', '23:00', 'MATA67' ],
	[ 'P05', '["a combinar"]', '00:00', '23:00', 'MATA67' ],
	[ 'P06', '["a combinar"]', '00:00', '23:00', 'MATA67' ],
	[ 'P07', '["a combinar"]', '00:00', '23:00', 'MATA67' ],
	[ 'P08', '["a combinar"]', '00:00', '23:00', 'MATA67' ],
	[ 'P09', '["a combinar"]', '00:00', '23:00', 'MATA67' ],
	[ 'P10', '["a combinar"]', '00:00', '23:00', 'MATA67' ],
	[ 'P11', '["a combinar"]', '00:00', '23:00', 'MATA67' ],
	[ 'P12', '["a combinar"]', '00:00', '23:00', 'MATA67' ],
	[ 'P13', '["a combinar"]', '00:00', '23:00', 'MATA67' ],
	[ 'P14', '["a combinar"]', '00:00', '23:00', 'MATA67' ],
	[ 'P15', '["a combinar"]', '00:00', '23:00', 'MATA67' ],
	[ 'P16', '["a combinar"]', '00:00', '23:00', 'MATA67' ],
	[ 'P17', '["a combinar"]', '00:00', '23:00', 'MATA67' ],
	[ 'P18', '["a combinar"]', '00:00', '23:00', 'MATA67' ],
	[ 'P19', '["a combinar"]', '00:00', '23:00', 'MATA67' ],
	[ 'P20', '["a combinar"]', '00:00', '23:00', 'MATA67' ],
	[ 'P21', '["a combinar"]', '00:00', '23:00', 'MATA67' ],
	[ 'P22', '["a combinar"]', '00:00', '23:00', 'MATA67' ],
	[ 'P23', '["a combinar"]', '00:00', '23:00', 'MATA67' ],
	[ 'P24', '["a combinar"]', '00:00', '23:00', 'MATA67' ],
	[ 'P25', '["a combinar"]', '00:00', '23:00', 'MATA67' ],
	[ 'P26', '["a combinar"]', '00:00', '23:00', 'MATA67' ],
	[ 'P27', '["a combinar"]', '00:00', '23:00', 'MATA67' ],
	[ 'P28', '["a combinar"]', '00:00', '23:00', 'MATA67' ],
	[ 'P29', '["a combinar"]', '00:00', '23:00', 'MATA67' ],
	[ 'P30', '["a combinar"]', '00:00', '23:00', 'MATA67' ],
	[ 'P31', '["a combinar"]', '00:00', '23:00', 'MATA67' ],
	[ 'P32', '["a combinar"]', '00:00', '23:00', 'MATA67' ],
	[ 'T01', '["a combinar"]', '00:00', '23:00', 'MATA67' ],
	[ 'T02', '["a combinar"]', '00:00', '23:00', 'MATA67' ],
	[ 'T03', '["a combinar"]', '00:00', '23:00', 'MATA67' ],
	[ 'T04', '["a combinar"]', '00:00', '23:00', 'MATA67' ],
	[ 'T05', '["a combinar"]', '00:00', '23:00', 'MATA67' ],
	[ 'T06', '["a combinar"]', '00:00', '23:00', 'MATA67' ],
	[ 'T07', '["a combinar"]', '00:00', '23:00', 'MATA67' ],
	[ 'T08', '["a combinar"]', '00:00', '23:00', 'MATA67' ],
	[ 'T09', '["a combinar"]', '00:00', '23:00', 'MATA67' ],
	[ 'T10', '["a combinar"]', '00:00', '23:00', 'MATA67' ],
	[ 'T11', '["a combinar"]', '00:00', '23:00', 'MATA67' ],
	[ 'T12', '["a combinar"]', '00:00', '23:00', 'MATA67' ],
	[ 'T13', '["a combinar"]', '00:00', '23:00', 'MATA67' ],
	[ 'T14', '["a combinar"]', '00:00', '23:00', 'MATA67' ],
	[ 'T15', '["a combinar"]', '00:00', '23:00', 'MATA67' ],
	[ 'T16', '["a combinar"]', '00:00', '23:00', 'MATA67' ],
	[ 'T17', '["a combinar"]', '00:00', '23:00', 'MATA67' ],
	[ 'T18', '["a combinar"]', '00:00', '23:00', 'MATA67' ],
	[ 'T19', '["a combinar"]', '00:00', '23:00', 'MATA67' ],
	[ 'T20', '["a combinar"]', '00:00', '23:00', 'MATA67' ],
	[ 'T21', '["a combinar"]', '00:00', '23:00', 'MATA67' ],
	[ 'T22', '["a combinar"]', '00:00', '23:00', 'MATA67' ],
	[ 'T23', '["a combinar"]', '00:00', '23:00', 'MATA67' ],
	[ 'T24', '["a combinar"]', '00:00', '23:00', 'MATA67' ],
	[ 'T25', '["a combinar"]', '00:00', '23:00', 'MATA67' ],
	[ 'T26', '["a combinar"]', '00:00', '23:00', 'MATA67' ],
	[ 'T27', '["a combinar"]', '00:00', '23:00', 'MATA67' ],
	[ 'T28', '["a combinar"]', '00:00', '23:00', 'MATA67' ],
	[ 'T29', '["a combinar"]', '00:00', '23:00', 'MATA67' ],
	[ 'T30', '["a combinar"]', '00:00', '23:00', 'MATA67' ],
	[ 'T31', '["a combinar"]', '00:00', '23:00', 'MATA67' ],
	[ 'T32', '["a combinar"]', '00:00', '23:00', 'MATA67' ],
]


class_subject_list.each do |number, days, hour_begins, hour_ends, code|
	ClassSubject.create( number: number, days: days, hour_begins: hour_begins, hour_ends: hour_ends, subject_id: Subject.find_by_code(code).id)
end


students_list = [
	[ 'Rafael', 216220012, 216220012 ],
	[ 'Vinícius', 151235, 151235],
	[ 'Jorel', 10241, 10241],
	[ 'Irmão do Jorel', 1511111, 1511111]
]

students_list.each do |name, cpf, registry|
	Student.create( name: name, cpf: cpf, registry: registry )
end

